[env]
BOOTLOADER_DIRECTORY = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/loader"
INITRD_DIRECTORY = "${BOOTLOADER_DIRECTORY}/initrd"

[tasks.default]
alias = "towboot"

# Build tasks

[tasks.link_members]
run_task = { name = "link", fork = true }
dependencies = [ "create-initrd-directory" ]

[tasks.create-initrd-directory]
command = "mkdir"
args = [ "-p", "${INITRD_DIRECTORY}" ]

[tasks.towboot]
cwd = "${BOOTLOADER_DIRECTORY}/towboot"
command = "./build.sh"
dependencies = [ "link_members", "initrd" ]

[tasks.grub]
cwd = "${BOOTLOADER_DIRECTORY}/grub"
command = "grub-mkrescue"
args = [ "-o", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os.iso", "iso/" ]
dependencies = [ "grub-copy-files" ]

[tasks.grub-copy-files]
cwd = "${BOOTLOADER_DIRECTORY}"
command = "cp"
args = [ "kernel.elf", "initrd.tar", "grub/iso/boot" ]
dependencies = [ "link_members", "initrd" ]

[tasks.initrd]
cwd = "${INITRD_DIRECTORY}"
command = "tar"
args = [ "-cf", "${BOOTLOADER_DIRECTORY}/initrd.tar", "hello", "shell", "uptime", "date" ]
dependencies = [ "link_members" ]

# Cleanup tasks

[tasks.clean]
dependencies = [ "clean_workspace", "clean_members" ]

[tasks.clean_workspace]
command = "rm"
args = [ "-rf",
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/d3os.img",
    "${BOOTLOADER_DIRECTORY}/kernel.elf",
    "${BOOTLOADER_DIRECTORY}/initrd.tar",
    "${BOOTLOADER_DIRECTORY}/grub/iso/boot/kernel.elf",
    "${BOOTLOADER_DIRECTORY}/grub/iso/boot/initrd.tar"  ]

[tasks.clean_members]
run_task = { name = "clean", fork = true }
