[package]
edition = "2024"
name = "input"
version = "0.1.0"
authors = ["Leon Lehnen", "Sebastian Keller <sebastian.keller@hhu.de>"]

[lib]
test = false
doctest = false
bench = false

[features]
default = ["userspace"]
userspace = ["dep:syscall", "dep:stream", "dep:bitflags", "dep:pc-keyboard"]

[dependencies]
# Local dependencies
syscall = { path = "../syscall", optional = true }
stream = { path = "../stream", optional = true }

# External dependencies
bitflags = { version = "2.9.0", optional = true }
pc-keyboard = { version = "0.8.0", optional = true }
