[package]
edition = "2024"
name = "input"
version = "0.1.0"
authors = ["Leon Lehnen", "Sebastian Keller <sebastian.keller@hhu.de>"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }
stream = { path = "../stream" }

# External dependencies
bitflags = "2.9.0"
pc-keyboard = "0.8.0"