use graphic::{
    color::{Color, BLUE, WHITE},
    lfb::DEFAULT_CHAR_HEIGHT,
};

pub const FG_COLOR: Color = WHITE;
pub const UNFOCUSED_BG_COLOR: Color = BLUE;

pub const WORKSPACE_SELECTION_LABEL_FONT_SCALE: (u32, u32) = (2, 2);
pub const HEIGHT_WORKSPACE_SELECTION_LABEL_WINDOW: u32 =
    DEFAULT_CHAR_HEIGHT * WORKSPACE_SELECTION_LABEL_FONT_SCALE.1 + 2;
