[EXTERN ___BSS_START__]
[EXTERN ___BSS_END__]
[EXTERN start]

; Kernel constants
STACK_SIZE equ 0x10000

; Multiboot2 constants
MULTIBOOT2_HEADER_MAGIC equ 0xe85250d6
MULTIBOOT2_HEADER_ARCHITECTURE equ 0
MULTIBOOT2_HEADER_LENGTH equ (boot - multiboot2_header)
MULTIBOOT2_HEADER_CHECKSUM equ -(MULTIBOOT2_HEADER_MAGIC + MULTIBOOT2_HEADER_ARCHITECTURE + MULTIBOOT2_HEADER_LENGTH)

; Multiboot2 tag types
MULTIBOOT2_TAG_TERMINATE equ 0
MULTIBOOT2_TAG_INFORMATION_REQUEST equ 1
MULTIBOOT2_TAG_ADDRESS equ 2
MULTIBOOT2_TAG_ENTRY_ADDRESS equ 3
MULTIBOOT2_TAG_FLAGS equ 4
MULTIBOOT2_TAG_FRAMEBUFFER equ 5
MULTIBOOT2_TAG_MODULE_ALIGNMENT equ 6
MULTIBOOT2_TAG_EFI_BOOT_SERVICES equ 7
MULTIBOOT2_TAG_EFI_I386_ENTRY_ADDRESS equ 8
MULTIBOOT2_TAG_EFI_AMD64_ENTRY_ADDRESS equ 9
MULTIBOOT2_TAG_RELOCATABLE_HEADER equ 10

; Multiboot2 request types
MULTIBOOT2_REQUEST_BOOT_COMMAND_LINE equ 1
MULTIBOOT2_REQUEST_BOOT_LOADER_NAME equ 2
MULTIBOOT2_REQUEST_MODULE equ 3
MULTIBOOT2_REQUEST_BASIC_MEMORY_INFORMATION equ 4
MULTIBOOT2_REQUEST_BIOS_BOOT_DEVICE equ 5
MULTIBOOT2_REQUEST_MEMORY_MAP equ 6
MULTIBOOT2_REQUEST_VBE_INFO equ 7
MULTIBOOT2_REQUEST_FRAMEBUFFER_INFO equ 8
MULTIBOOT2_REQUEST_ELF_SYMBOLS equ 9
MULTIBOOT2_REQUEST_APM_TABLE equ 10
MULTIBOOT2_REQUEST_EFI_32_BIT_SYSTEM_TABLE_POINTER equ 11
MULTIBOOT2_REQUEST_EFI_64_BIT_SYSTEM_TABLE_POINTER equ 12
MULTIBOOT2_REQUEST_SMBIOS_TABLES equ 13
MULTIBOOT2_REQUEST_ACPI_OLD_RSDP equ 14
MULTIBOOT2_REQUEST_ACPI_NEW_RSDP equ 15
MULTIBOOT2_REQUEST_NETWORKING_INFORMATION equ 16
MULTIBOOT2_REQUEST_EFI_MEMORY_MAP equ 17
MULTIBOOT2_REQUEST_EFI_BOOT_SERVICES_NOT_TERMINATED equ 18
MULTIBOOT2_REQUEST_EFI_32_BIT_IMAGE_HANDLE_POINTER equ 19
MULTIBOOT2_REQUEST_EFI_64_BIT_IMAGE_HANDLE_POINTER equ 20
MULTIBOOT2_REQUEST_IMAGE_LOAD_BASE_PHYSICAL_ADDRESS equ 21

; Multiboot2 tag flags
MULTIBOOT2_TAG_FLAG_REQUIRED equ 0x00
MULTIBOOT2_TAG_FLAG_OPTIONAL equ 0x01

; Multiboot2 console flags
MULTIBOOT2_CONSOLE_FLAG_FORCE_TEXT_MODE equ 0x01
MULTIBOOT2_CONSOLE_FLAG_SUPPORT_TEXT_MODE equ 0x02

; Multiboot2 framebuffer options
MULTIBOOT2_GRAPHICS_MODE   equ 0
MULTIBOOT2_GRAPHICS_WIDTH  equ 800
MULTIBOOT2_GRAPHICS_HEIGHT equ 600
MULTIBOOT2_GRAPHICS_BPP    equ 32

[SECTION .text]
[BITS 64]

multiboot2_header:
    ; Header
    align 8
    dd MULTIBOOT2_HEADER_MAGIC
    dd MULTIBOOT2_HEADER_ARCHITECTURE
    dd MULTIBOOT2_HEADER_LENGTH
    dd MULTIBOOT2_HEADER_CHECKSUM

    ; EFI amd64 entry address tag
    align 8
    dw MULTIBOOT2_TAG_EFI_AMD64_ENTRY_ADDRESS
    dw MULTIBOOT2_TAG_FLAG_REQUIRED
    dd 12
    dd (boot)

    ; EFI boot services tag
    align 8
    dw MULTIBOOT2_TAG_EFI_BOOT_SERVICES
    dw MULTIBOOT2_TAG_FLAG_REQUIRED
    dd 8

    ; Information request tag (required)
    align 8
    dw MULTIBOOT2_TAG_INFORMATION_REQUEST
    dw MULTIBOOT2_TAG_FLAG_REQUIRED
    dd 44
    dd MULTIBOOT2_REQUEST_BOOT_COMMAND_LINE
    dd MULTIBOOT2_REQUEST_MODULE
    dd MULTIBOOT2_REQUEST_MEMORY_MAP
    dd MULTIBOOT2_REQUEST_FRAMEBUFFER_INFO
    dd MULTIBOOT2_REQUEST_ACPI_OLD_RSDP
    dd MULTIBOOT2_REQUEST_ACPI_NEW_RSDP
    dd MULTIBOOT2_REQUEST_EFI_BOOT_SERVICES_NOT_TERMINATED
    dd MULTIBOOT2_REQUEST_EFI_64_BIT_SYSTEM_TABLE_POINTER
    dd MULTIBOOT2_REQUEST_EFI_64_BIT_IMAGE_HANDLE_POINTER

    ; Information request tag (optional)
    align 8
    dw MULTIBOOT2_TAG_INFORMATION_REQUEST
    dw MULTIBOOT2_TAG_FLAG_OPTIONAL
    dd 20
    dd MULTIBOOT2_REQUEST_BOOT_LOADER_NAME
    dd MULTIBOOT2_REQUEST_EFI_BOOT_SERVICES_NOT_TERMINATED
    dd MULTIBOOT2_REQUEST_EFI_MEMORY_MAP

    ; Framebuffer tag
    align 8
    dw MULTIBOOT2_TAG_FRAMEBUFFER
    dw MULTIBOOT2_TAG_FLAG_REQUIRED
    dd 20
    dd MULTIBOOT2_GRAPHICS_WIDTH
    dd MULTIBOOT2_GRAPHICS_HEIGHT
    dd MULTIBOOT2_GRAPHICS_BPP

    ; Module alignment tag
    align 8
    dw MULTIBOOT2_TAG_MODULE_ALIGNMENT
    dw MULTIBOOT2_TAG_FLAG_OPTIONAL
    dd 8

    ; Termination tag
    align 8
    dw MULTIBOOT2_TAG_TERMINATE
    dw MULTIBOOT2_TAG_FLAG_REQUIRED
    dd 8

boot:
    cld ; Expected by GCC
    cli ; Disable interrupts

    ; Clear BSS section
    mov rdi, ___BSS_START__
clear_bss:
    mov byte [rdi], 0
    inc rdi
    cmp rdi, ___BSS_END__
    jne clear_bss

    ; Switch stack to our own stack, because the EFI stack may be located inside
    ; reserved memory and will thus be ignored by our paging implementation.
    mov rsp, init_stack.end

    ; Call rust function with multiboot2 magic number and address (initially located in eax and ebx)
    xor rdi, rdi
    xor rsi, rsi
    mov edi, eax
    mov esi, ebx
    call start

[SECTION .bss]

global init_stack:data (init_stack.end - init_stack)
init_stack:
	  resb STACK_SIZE
.end: