[package]
name = "text_buffer"
version = "0.1.0"
edition = "2024"
authors = ["Julius Carl Drodofsky <julius@drodofsky.xyz>"]

[lib]
test = true
doctest = false
bench = false

[dependencies]

[features]
default = ["alloc"]
alloc = []
