[package]
edition = "2024"
name = "logger"
version = "0.1.0"
authors = ["Sebastian Keller <sebastian.keller@hhu.de>"]

[lib]
test = false
doctest = false
bench = false

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }

# External depencies
num_enum = { version = "0.7", default-features = false }
