[package]
edition = "2021"
name = "io"
version = "0.1.0"
authors = ["Michael Schöttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[dependencies]
# Local dependencies
syscall = { path = "../syscall" }

# External dependencies
spin = "0.9.8"