[package]
edition = "2021"
name = "thread"
version = "0.1.0"
authors = ["Michael Schöttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]


[dependencies]
syscall = { path = "../syscall" }