[package]
edition = "2024"
name = "runtime"
version = "0.1.0"
authors = ["Michael Schöttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[dependencies]
# Local dependencies
terminal = { path = "../terminal" }
syscall = { path = "../syscall" }
concurrent = { path = "../concurrent" }
stream = { path = "../stream" }

# External dependencies
linked_list_allocator = { version = "0.10.5", features = ["alloc_ref"] }